apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: semantic-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: localhost:32000/blog:dev
          ports: 
          - containerPort: 8080
          env: 
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: semantic-blog
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd         
