apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: semantic-blog
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: semantic-blog
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP